import React from 'react'
import Nav from './Nav'
import { Link } from 'react-router-dom'
const About = () => {
  return (
    <div className='aboutpage'>
        <h1>About Bhuvan </h1>
        <Nav/>
        <section id='about-container'>
        <h2>Overview</h2>
        <p id='para'>
            Welcome to Bhuvan, your gateway to explore the diverse geography of India through a cutting-edge web-based
            utility developed by the Indian Space Research Organisation (ISRO).
        </p>

        <h2>Features</h2>
        <ul>
            <li><strong>Geospatial Layers:</strong> Bhuvan provides thematic maps related to disasters, agriculture,
                water resources, land cover, and processed satellite data generated by ISRO.</li>
            <li><strong>Government Collaboration:</strong> Bhuvan collaborates with different sections of the Government
                of India, facilitating the use of geospatial technology.</li>
            <li><strong>Imagery Resolution:</strong> With spatial resolutions ranging up to an impressive 1 meter,
                Bhuvan offers detailed imagery of Indian locations.</li>
        </ul>

       

        <h2>Join the Bhuvan Community</h2>
        <p id='para'>
            Bhuvan welcomes users to explore and contribute. While visualization of maps doesn't require login, users can
            register to download satellite data and products. A discussion forum provides a platform for users to share
            experiences and seek assistance.
        </p>

        <p>
            Experience India like never before with Bhuvan—a powerful tool bringing geospatial technology to your
            fingertips.
        </p>

        <div id='button'>
            <h5 ><Link style={{textDecoration: 'none ',color:"white",fontWeight:"bold"}} to="/">Explore Bhuvan Chatbot</Link></h5>
        </div>
    </section>

    </div>
  )
}

export default About